In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Innlastning av dataset #

In [11]:
df_links_small = pd.read_csv('data/links_small.csv')
df_links_small.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [14]:
df_links = pd.read_csv('data/links.csv')
df_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [12]:
df_ratings_small = pd.read_csv('data/ratings_small.csv')
df_ratings_small.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [13]:
df_ratings = pd.read_csv('data/ratings.csv')
df_ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

-------------------------------------------------

# Utforskning av data #
Utforsker de ulike csv-filene ved hjelp av .shape, .head(), .dtypes og .info()

## Links_small ##

### .shape ###

In [ ]:
df_links_small.shape

### .head() ###

In [ ]:
df_links_small.head()

### .dtypes ###

In [ ]:
df_links_small.dtypes

### .info() ###

In [ ]:
df_links_small.info()

## Links ##

### .shape ###

In [ ]:
df_links.shape

### .head() ###

In [ ]:
df_links.head()

### .dtypes ###

In [ ]:
df_links.dtypes

### .info() ###

In [ ]:
df_links.info()

## Ratings_small ##

### .shape ###

In [ ]:
df_ratings_small.shape

### .head() ###

In [ ]:
df_ratings_small.head()

### .dtypes ###

In [ ]:
df_ratings_small.dtypes

### .info() ###

In [ ]:
df_ratings_small.info()

## Ratings ##

### .shape ###

In [ ]:
df_ratings.shape

### .head() ###

In [ ]:
df_ratings.head()

### .dtypes ###

In [ ]:
df_ratings.dtypes

### .info() ###

In [ ]:
df_ratings.info()